// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwgfdNs4pRnnT5lBTAALucq5XSC_PNcM',
    appId: '1:103355382424:web:ccbb743fdb408afa2deeed',
    messagingSenderId: '103355382424',
    projectId: 'finalproject-90c52',
    authDomain: 'finalproject-90c52.firebaseapp.com',
    storageBucket: 'finalproject-90c52.firebasestorage.app',
    measurementId: 'G-0NSLWZZ75F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSOSHIR1WERb-2wr_9X-Of7S_3l8aq_-k',
    appId: '1:103355382424:ios:d9933631925d94a52deeed',
    messagingSenderId: '103355382424',
    projectId: 'finalproject-90c52',
    storageBucket: 'finalproject-90c52.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSOSHIR1WERb-2wr_9X-Of7S_3l8aq_-k',
    appId: '1:103355382424:ios:d9933631925d94a52deeed',
    messagingSenderId: '103355382424',
    projectId: 'finalproject-90c52',
    storageBucket: 'finalproject-90c52.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );
}
